name: Submit twin document hash to DLT

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11.2'
    - name: Setup git
      run: |
        git config --local user.email "bot@twinbase.org"
        git config --local user.name "twinbase-bot"
    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Get Secrets from Bitwarden Secrets Manager
      uses: bitwarden/sm-action@v1
      with:
        access_token: ${{ secrets.BW_ACCESS_TOKEN }}
        secrets: |
          ca1ac4f9-4d8e-449f-8ba6-afe900ad5152 > DLT_PRIVATE_KEY
    - name: Submit hash
      env:
          DLT_TYPE: ${{ vars.DLT_TYPE }}
          DLT_HTTP_NODE: ${{ vars.DLT_HTTP_NODE }}
          DLT_GAS_PROVIDED: ${{ vars.DLT_GAS_PROVIDED }}
          DLT_PRIVATE_KEY: $DLT_PRIVATE_KEY
      run: |
        python ${GITHUB_WORKSPACE}/.github/store-hash-to-dlt.py
        git add -A
        git commit -m "Autoupdate salt and hash info" -a || echo "Warning: git commit returned error code $? (Hopefully nothing to commit)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
